const canvas=document.getElementById("game"),ctx=canvas.getContext("2d"),W=canvas.width,H=canvas.height;
const menu=document.getElementById("menu"),shop=document.getElementById("shop"),gameOver=document.getElementById("gameOver"),hud=document.getElementById("hud");
const scoreEl=document.getElementById("score"),bestEl=document.getElementById("bestScore"),topCoinsEl=document.getElementById("topCoins"),shopCoinsEl=document.getElementById("shopCoins"),runCoinsEl=document.getElementById("runCoins"),earnedCoinsEl=document.getElementById("earnedCoins"),finalScoreEl=document.getElementById("finalScore"),finalBestEl=document.getElementById("finalBest"),skinsEl=document.getElementById("skins"),menuBird=document.getElementById("menuBird");
const SKINS=[
{id:"yellow",name:"Classic",price:0,body:"#ffd34e",wing:"#f0aa35",beak:"#ff8d3d",icon:"🐦"},
{id:"blue",name:"Ocean",price:25,body:"#54b8ff",wing:"#2788d4",beak:"#ffb347",icon:"🪽"},
{id:"red",name:"Blaze",price:50,body:"#ff5f62",wing:"#d83d47",beak:"#ffc04d",icon:"🐤"},
{id:"purple",name:"Galaxy",price:100,body:"#b178ff",wing:"#7441c7",beak:"#ffd34e",icon:"🦄"}];
const state={
mode:"menu",score:0,best:Number(localStorage.getItem("skyHopperBest")||0),
coins:Number(localStorage.getItem("skyHopperCoins")||0),runCoins:0,
owned:JSON.parse(localStorage.getItem("skyHopperOwned")||'["yellow"]'),
selected:localStorage.getItem("skyHopperSelected")||"yellow",lastTime:0,spawnTimer:0,groundOffset:0,flash:0,shake:0};
const bird={x:130,y:H/2,r:18,vy:0,rotation:0},pipes=[],coins=[],particles=[],clouds=[];
for(let i=0;i<7;i++)clouds.push({x:Math.random()*W,y:70+Math.random()*220,w:55+Math.random()*85,speed:8+Math.random()*12});

function save(){localStorage.setItem("skyHopperCoins",state.coins);localStorage.setItem("skyHopperOwned",JSON.stringify(state.owned));localStorage.setItem("skyHopperSelected",state.selected)}
function updateCoins(){topCoinsEl.textContent=state.coins;shopCoinsEl.textContent=state.coins;runCoinsEl.textContent=state.runCoins;menuBird.textContent=(SKINS.find(s=>s.id===state.selected)||SKINS[0]).icon}
function renderShop(){skinsEl.innerHTML="";for(const s of SKINS){const owned=state.owned.includes(s.id),selected=state.selected===s.id,card=document.createElement("div");card.className="skin";card.innerHTML=`<div class="skin-icon">${s.icon}</div><div class="skin-name">${s.name}</div><div class="skin-price">${s.price?"🪙 "+s.price:"FREE"}</div><button class="${selected?"selected":owned?"owned":""}">${selected?"SELECTED":owned?"SELECT":"BUY"}</button>`;card.querySelector("button").onclick=()=>{if(owned){state.selected=s.id;save();updateCoins();renderShop();return}if(state.coins<s.price){card.querySelector("button").textContent=`NEED ${s.price-state.coins} MORE`;setTimeout(renderShop,900);return}state.coins-=s.price;state.owned.push(s.id);state.selected=s.id;save();updateCoins();renderShop()};skinsEl.appendChild(card)}}
function openShop(){state.mode="shop";menu.classList.add("hidden");gameOver.classList.add("hidden");hud.classList.add("hidden");shop.classList.remove("hidden");updateCoins();renderShop()}
function closeShopView(){state.mode="menu";shop.classList.add("hidden");menu.classList.remove("hidden");updateCoins()}
function resetGame(){state.mode="playing";state.score=0;state.runCoins=0;state.spawnTimer=0;state.groundOffset=0;state.flash=0;state.shake=0;bird.x=130;bird.y=H/2;bird.vy=0;bird.rotation=0;pipes.length=0;coins.length=0;particles.length=0;scoreEl.textContent="0";runCoinsEl.textContent="0";menu.classList.add("hidden");shop.classList.add("hidden");gameOver.classList.add("hidden");hud.classList.remove("hidden");flap()}
function endGame(){if(state.mode!=="playing")return;state.mode="gameover";state.shake=12;state.flash=.18;state.coins+=state.runCoins;if(state.score>state.best){state.best=state.score;localStorage.setItem("skyHopperBest",state.best)}save();finalScoreEl.textContent=state.score;finalBestEl.textContent=state.best;earnedCoinsEl.textContent=state.runCoins;bestEl.textContent=state.best;topCoinsEl.textContent=state.coins;gameOver.classList.remove("hidden");hud.classList.add("hidden")}
function flap(){if(state.mode!=="playing")return;bird.vy=-430;for(let i=0;i<5;i++)particles.push({x:bird.x-14,y:bird.y+5,vx:-70-Math.random()*80,vy:(Math.random()-.5)*80,life:.35+Math.random()*.2,maxLife:.55,size:2+Math.random()*3})}
function spawnPipe(){const gap=Math.max(150,190-state.score*1),minTop=80,maxTop=H-120-gap,top=minTop+Math.random()*(maxTop-minTop),p={x:W+40,width:74,top,bottom:top+gap,passed:false};pipes.push(p);coins.push({x:p.x+p.width+24,y:top+gap/2+(Math.random()-.5)*Math.min(35,gap*.18),r:12,collected:false,spin:Math.random()*Math.PI})}
function collectCoin(c){if(c.collected)return;c.collected=true;state.runCoins++;runCoinsEl.textContent=state.runCoins;for(let i=0;i<12;i++)particles.push({x:c.x,y:c.y,vx:(Math.random()-.5)*180,vy:(Math.random()-.5)*180,life:.35+Math.random()*.35,maxLife:.7,size:2+Math.random()*3})}
function update(dt){
for(const c of clouds){c.x-=c.speed*dt;if(c.x+c.w<-10){c.x=W+20;c.y=70+Math.random()*220}}
for(const p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=120*dt;p.life-=dt}for(let i=particles.length-1;i>=0;i--)if(particles[i].life<=0)particles.splice(i,1);
state.flash=Math.max(0,state.flash-dt);state.shake=Math.max(0,state.shake-30*dt);if(state.mode!=="playing")return;
bird.vy+=1150*dt;bird.y+=bird.vy*dt;bird.rotation=Math.max(-.5,Math.min(1.2,bird.vy/650));
state.spawnTimer+=dt;if(state.spawnTimer>=1.45){state.spawnTimer=0;spawnPipe()}
const speed=Math.min(225+Math.floor(state.score/5)*35,400);
for(const p of pipes){p.x-=speed*dt;if(!p.passed&&p.x+p.width<bird.x){p.passed=true;state.score++;scoreEl.textContent=state.score}const hitX=bird.x+bird.r>p.x&&bird.x-bird.r<p.x+p.width,hitY=bird.y-bird.r<p.top||bird.y+bird.r>p.bottom;if(hitX&&hitY)endGame()}
for(const c of coins){c.x-=speed*dt;c.spin+=dt*7;const dx=bird.x-c.x,dy=bird.y-c.y;if(!c.collected&&Math.hypot(dx,dy)<bird.r+c.r)collectCoin(c)}
while(pipes.length&&pipes[0].x+pipes[0].width<-30)pipes.shift();while(coins.length&&coins[0].x<-40)coins.shift();
if(bird.y-bird.r<=0||bird.y+bird.r>=H-70)endGame();state.groundOffset=(state.groundOffset+speed*dt)%48}
function drawBackground(){const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,"#75d1ff");g.addColorStop(.58,"#b8ebff");g.addColorStop(1,"#e9f9ff");ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.fillStyle="rgba(255,255,255,.22)";ctx.beginPath();ctx.arc(390,95,55,0,Math.PI*2);ctx.fill();for(const c of clouds){ctx.fillStyle="rgba(255,255,255,.65)";ctx.beginPath();ctx.ellipse(c.x,c.y,c.w*.45,19,0,0,Math.PI*2);ctx.ellipse(c.x-c.w*.25,c.y+2,c.w*.28,15,0,0,Math.PI*2);ctx.ellipse(c.x+c.w*.22,c.y+1,c.w*.32,17,0,0,Math.PI*2);ctx.fill()}ctx.fillStyle="#9bdf87";ctx.beginPath();ctx.moveTo(0,H-110);ctx.quadraticCurveTo(120,H-165,240,H-105);ctx.quadraticCurveTo(350,H-55,W,H-125);ctx.lineTo(W,H);ctx.lineTo(0,H);ctx.fill();ctx.fillStyle="#77c96b";ctx.beginPath();ctx.moveTo(0,H-82);ctx.quadraticCurveTo(140,H-120,280,H-70);ctx.quadraticCurveTo(400,H-30,W,H-90);ctx.lineTo(W,H);ctx.lineTo(0,H);ctx.fill()}
function drawPipe(x,y,h,up=false){const w=74,capH=24,capW=84,capX=x-(capW-w)/2;ctx.fillStyle="#3eaf61";ctx.fillRect(x,y,w,h);ctx.fillStyle="#58cf78";ctx.fillRect(x+9,y,12,h);ctx.fillStyle="#2b8c4d";ctx.fillRect(x+w-11,y,11,h);const cy=up?y+h-capH:y;ctx.fillStyle="#319b55";ctx.fillRect(capX,cy,capW,capH);ctx.fillStyle="#65dc83";ctx.fillRect(capX+9,cy+4,12,capH-7)}
function drawPipes(){for(const p of pipes){drawPipe(p.x,0,p.top,true);drawPipe(p.x,p.bottom,H-70-p.bottom,false)}}
function drawCoins(){for(const c of coins){if(c.collected)continue;const s=Math.abs(Math.cos(c.spin))*.35+.65;ctx.save();ctx.translate(c.x,c.y);ctx.scale(s,1);ctx.fillStyle="#ffd34e";ctx.beginPath();ctx.arc(0,0,c.r,0,Math.PI*2);ctx.fill();ctx.strokeStyle="#e4a82e";ctx.lineWidth=3;ctx.stroke();ctx.fillStyle="#fff1a8";ctx.font="bold 12px sans-serif";ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText("$",0,1);ctx.restore()}}
function drawGround(){ctx.fillStyle="#e8c76c";ctx.fillRect(0,H-70,W,70);ctx.fillStyle="#d8b75a";for(let x=-48+state.groundOffset;x<W+48;x+=48){ctx.fillRect(x,H-48,24,6);ctx.fillRect(x+27,H-28,21,6)}ctx.fillStyle="#77c96b";ctx.fillRect(0,H-70,W,10);ctx.fillStyle="#5caf5b";ctx.fillRect(0,H-70,W,4)}
function drawBird(){const s=SKINS.find(x=>x.id===state.selected)||SKINS[0];ctx.save();ctx.translate(bird.x,bird.y);ctx.rotate(bird.rotation);ctx.fillStyle=s.body;ctx.beginPath();ctx.arc(0,0,bird.r,0,Math.PI*2);ctx.fill();ctx.fillStyle=s.wing;ctx.beginPath();ctx.ellipse(-5,7,11,7,-.3,0,Math.PI*2);ctx.fill();ctx.fillStyle="#fff";ctx.beginPath();ctx.arc(8,-7,6,0,Math.PI*2);ctx.fill();ctx.fillStyle="#18212f";ctx.beginPath();ctx.arc(10,-7,2.8,0,Math.PI*2);ctx.fill();ctx.fillStyle=s.beak;ctx.beginPath();ctx.moveTo(16,-1);ctx.lineTo(31,4);ctx.lineTo(16,8);ctx.closePath();ctx.fill();ctx.restore()}
function drawParticles(){for(const p of particles){ctx.globalAlpha=Math.max(0,p.life/p.maxLife);ctx.fillStyle="#fff";ctx.beginPath();ctx.arc(p.x,p.y,p.size,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1}
function render(){ctx.save();if(state.shake>0)ctx.translate((Math.random()-.5)*state.shake,(Math.random()-.5)*state.shake);drawBackground();drawPipes();drawCoins();drawGround();drawParticles();drawBird();if(state.flash>0){ctx.fillStyle=`rgba(255,255,255,${state.flash})`;ctx.fillRect(0,0,W,H)}ctx.restore()}
function loop(t){const dt=Math.min((t-state.lastTime)/1000||0,.033);state.lastTime=t;update(dt);render();requestAnimationFrame(loop)}
document.getElementById("playBtn").onclick=resetGame;document.getElementById("shopBtn").onclick=openShop;document.getElementById("closeShop").onclick=closeShopView;document.getElementById("againBtn").onclick=resetGame;
document.getElementById("menuBtn").onclick=()=>{state.mode="menu";gameOver.classList.add("hidden");hud.classList.add("hidden");menu.classList.remove("hidden");bird.y=H/2;bird.vy=0;pipes.length=0;coins.length=0;updateCoins()};
canvas.addEventListener("pointerdown",e=>{e.preventDefault();if(state.mode==="playing")flap()});
window.addEventListener("keydown",e=>{if(e.code==="Space"||e.code==="ArrowUp"){e.preventDefault();if(state.mode==="playing")flap()}if(e.code==="Enter"&&state.mode!=="playing"&&state.mode!=="shop")resetGame()});
bestEl.textContent=state.best;updateCoins();renderShop();render();requestAnimationFrame(loop);
